# -*- coding: utf-8 -*-
"""testV004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mv2qMGkSRRaXhdgZVKv3rdcLM3xdgzFN
"""

from google.colab import drive 
drive.mount('/drive')

from sklearn.metrics import accuracy_score

import pandas as pd

import numpy as np

from sklearn.datasets import make_classification

from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn2pmml import sklearn2pmml,make_pmml_pipeline

import warnings
warnings.filterwarnings("ignore")

"""---

## Load dataset
"""

!

data = pd.read_csv('/content/sample_data/preprocessedDataset.csv')
data

"""---

## Separation data
"""

X = data.iloc[:,4:]
X

y = data.iloc[:,1]
y

"""---

## shape dataset
"""

X.shape

y.shape

"""---

## split data
"""

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,random_state=1)

X_train.shape

y_train.shape

X_test.shape

y_test.shape

"""---

## create model
"""

clf = MLPClassifier(random_state=1, max_iter=300)

"""## train model"""

clf.fit(X_train, y_train)

"""---

## predict
"""

pr = clf.predict(X_test)
pr

y_test

score = accuracy_score(y_test, pr)
score

"""---

## pipelien create
"""

mlp_pipline = Pipeline([('imputer',SimpleImputer()),('mlpClassifier',MLPClassifier())])

"""---

## fit pipeline model
"""

mlp_pipline.fit(X_train, y_train)

"""---

## predict pipeline model
"""

mlp_pipline.predict(X_test)

"""---

## make pmml model
"""

sklearn2pmml(make_pmml_pipeline(mlp_pipline), "MLPClassifierVehicleIdentification.pmml")

!ls

"""---"""